# SAM build file for searchArchive
# Copyright (C) 2018-2023 Mark McIntyre
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  getFireballFiles:
    Type: AWS::Serverless::Function
    Properties:
      Handler: getFireballFiles.lambda_handler
      Runtime: python3.8
      FunctionName: getFireballFiles
      Description: API backend that retrieves fireball files matching a pattern if available
      Timeout: 120
      Policies: AmazonS3ReadOnlyAccess
      Environment:
        Variables:
          ARCHBUCKET: ukmda-shared
          MPLCONFIGDIR: /tmp/mpl
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/'
            Method: get
            RequestParameters: [
              'method.request.querystring.pattern': {Required: true},
            ]
      Tags:
        billingtag: "ukmda"
    Metadata:
      BuildMethod: python3.8
