    winsrcdir: /mnt/e/dev/meteorhunting/UKmon-shared/usermgmt/windows
    windestdir: /mnt/f/videos/MeteorCam/usermgmt
    destdir: /home/ec2-user/keymgmt
    srcbucket: ukmda-shared
    livebucket: ukmda-live
    websitebucket: ukmda-website
    liveprofile: ukmon-markmcintyre
    archprofile: ukmda_admin
    helper: ukmonhelper2
    serverip: "3.11.55.160"