# Copyright (C) 2018-2023 Mark McIntyre
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "matchPickleApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17e011f5cwvp1"
s3_prefix = "matchPickleApi"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = true
#image_repositories = []
image_repositories = ["matchPickleApi=822069317839.dkr.ecr.eu-west-1.amazonaws.com/matchpickleapi60c45b31/matchpickleapi60c45b31repo"]
