# SAM build file for searchArchive
# Copyright (C) 2018-2023 Mark McIntyre
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  camDetails:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      FunctionName: camDetails
      Description: API backend that manages cameras
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          ARCHBUCKET: ukmda-shared
          MPLCONFIGDIR: /tmp/mpl
      Tags:
        billingtag: "ukmon"
      Role: arn:aws:iam::822069317839:role/service-role/S3FullAccess
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/camdetails'
            Method: get
    Metadata:
      BuildMethod: python3.8
      Dockerfile: Dockerfile
      DockerContext: ./pythoncode
      DockerTag: python3.8-v1

