---
- hosts: "{{host | default ('ukmonhelper2')}}"
  vars:
    srcdir: /mnt/e/dev/meteorhunting/UKMON-shared
  tasks:
  - name: import dev variables 
    include_vars: ./dev-vars.yml
    tags: dev
  - name: import prod variables
    include_vars: ./prod-vars.yml
    tags: prod
  - name: Ensures {{destdir}} exists
    file: path={{destdir}} state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/logs exists
    file: path={{destdir}}/logs state=directory  
  - name: Ensures {{destdir}}/data/reports/ exists
    file: path={{destdir}}/data/reports/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/admin/ exists
    file: path={{destdir}}/data/admin/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/single/ exists
    file: path={{destdir}}/data/single/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/matched/ exists
    file: path={{destdir}}/data/matched/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/browse/ exists
    file: path={{destdir}}/data/browse/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/browse/annual/ exists
    file: path={{destdir}}/data/browse/annual/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/browse/daily/ exists
    file: path={{destdir}}/data/browse/daily/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/browse/monthly/ exists
    file: path={{destdir}}/data/browse/monthly/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/browse/showers/ exists
    file: path={{destdir}}/data/browse/showers/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/dailyreports/ exists
    file: path={{destdir}}/data/dailyreports/ state=directory  
    tags: [dev,prod]
  - name: Ensures {{destdir}}/data/shwrinfo/ exists
    file: path={{destdir}}/data/shwrinfo/ state=directory  
    tags: [dev,prod]
  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [dev,prod]
    with_items:
    - {src: '{{srcdir}}/archive/static_content/', dest: '{{destdir}}/static_content/', mode: '754', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/ukmon_pylib/', dest: '{{destdir}}/ukmon_pylib/', mode: '644', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/analysis/', dest: '{{destdir}}/analysis/', mode: '754', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/cronjobs/', dest: '{{destdir}}/cronjobs/', mode: '754', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/utils/', dest: '{{destdir}}/utils/', mode: '754', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/website/', dest: '{{destdir}}/website/', mode: '754', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/shwrinfo/', dest: '{{destdir}}/data/shwrinfo/', mode: '754', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/share/', dest: '{{destdir}}/share/', mode: '754', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/database/', dest: '{{destdir}}/database/', mode: '754', backup: no, directory_mode: yes }
    - {src: '{{srcdir}}/archive/setup/', dest: '{{destdir}}/setup/', mode: '754', backup: no, directory_mode: yes }
