- hosts: "{{host | default ('ukmonhelper')}}"
  vars:
    srcdir: /mnt/e/dev/meteorhunting/UKMON-shared/archive
  tasks:
  - name: import dev variables 
    include_vars: dev-vars.yml
    tags: dev
  - name: import prod variables
    include_vars: prod-vars.yml
    tags: prod
  - name: Ensures {{destdir}} exists
    file: path={{destdir}} state=directory  
    tags: [dev,prod]

  - name: Copy files
    copy: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
    tags: [dev,prod]
    with_items:
    - {src: '{{srcdir}}/utils/makeConfig.sh', dest: '{{destdir}}/utils/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/utils/stopstart-calcengine.sh', dest: '{{destdir}}/utils/', mode: '754', backup: yes }
    - {src: '{{srcdir}}/.bashrc', dest: '/home/ec2-user', mode: '644', backup: yes }
    - {src: '{{srcdir}}/.bash_aliases', dest: '/home/ec2-user', mode: '644', backup: no }
    
  - name: create Config file
    shell: '{{destdir}}/utils/makeConfig.sh {{env}}'
    tags: [dev,prod]
