# Copyright (C) 2018-2023 Mark McIntyre
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "camDetails"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-17e011f5cwvp1"
s3_prefix = "camDetails"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = true
#image_repositories = []
image_repositories = ["camDetails=822069317839.dkr.ecr.eu-west-1.amazonaws.com/ukmon/camDetails"]
