# Copyright (C) 2018-2023 Mark McIntyre
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ftpToUkmon"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1ulna2hoktme4"
s3_prefix = "ftpToUkmon"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
#image_repository = "822069317839.dkr.ecr.eu-west-2.amazonaws.com/ukmon/ftptoukmon"
profile = "ukmda_admin"
image_repositories = ["ftpToUkmon=183798037734.dkr.ecr.eu-west-2.amazonaws.com/lambdas/ftptoukmon"]
