# Copyright (C) 2018-2023 Mark McIntyre
version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "matchPickleApi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cy2k1achj9nv"
s3_prefix = "matchPickleApi"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
disable_rollback = true
image_repositories = ["matchPickleApi=183798037734.dkr.ecr.eu-west-1.amazonaws.com/apis/matchpickleapi"]
profile = "ukmda_admin"
