name: automated_testing

on:
  push:
    branches:
      - markmac99

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  linuxtests:
    runs-on: [testpi4ukm]
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./ukmon_meteortools/tests/*.sh
      - run: ./ukmon_meteortools/tests/runTests.sh 
  apitests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./tests/*.sh
      - run: ./tests/api_tests.sh
