name: automated_testing
env:
  AWS_REGION: eu-west-2
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - markmac99
jobs:
  conttests:
    runs-on: ubuntu-latest
    container:
      image: docker.io/markmac99/ukmdatester
      credentials:
        username: ${{ secrets.DH_LOGIN_MM }}
        password: ${{ secrets.DH_PATT_MM }}
      env:
        DATADIR: /tmp/data
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::183798037734:role/testingRole
          role-session-name: github_aws_testing
          aws-region: ${{ env.AWS_REGION }}
      - name: remote tests
        run: |
          chmod +x /tests.sh
          (ls /tests.sh && echo Found test script) || (echo No test script) 
          mkdir -p /tmp/data/{consolidated,admin,reports,matched}
          aws s3 cp s3://ukmda-shared/consolidated/camera-details.csv /tmp/data/consolidated/ --quiet
          aws s3 cp  s3://ukmda-website/reports/stations/cameraLocs.json /tmp/data/admin/ --quiet
          aws s3 cp s3://ukmda-shared/matches/matchedpq/matches-full-2023.parquet.snap /tmp/data/matched/ --quiet
          /tests.sh
  apitests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code 
        uses: actions/checkout@v3
      - name: run api tests
        run: |
          chmod +x ./tests/api_tests.sh
          ./tests/api_tests.sh
