name: automated_testing

on:
  push:
    branches:
      - markmac99
jobs:
  conttests:
    runs-on: ubuntu-latest
    container:
      image: docker.io/markmac99/ukmdatester
      credentials:
        username: markmac99
        password: ${{ secrets.GHCR_PAT_MM }}
      env:
        TESTSCRIPT: somefile.sh
    steps:
      - name: Check for dockerenv file
        run: (ls /tests.sh && echo Found test script) || (echo No test script) 
  apitests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./tests/*.sh
      - run: ./tests/api_tests.sh
  #lnxtests:
  #  runs-on: lnx64
  #  steps:
  #    - uses: actions/checkout@v3
  #    - run: chmod +x ./tests/*.sh
  #    - run: ./tests/lnx_tests.sh
    
