name: automated_testing

on:
  push:
    branches:
      - markmac99
jobs:
  apitests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./tests/*.sh
      - run: ./tests/api_tests.sh
  lnxtests:
    runs-on: X64
    steps:
      - uses: actions/checkout@v3
      - run: chmod +x ./tests/*.sh
      - run: ./tests/lnx_tests.sh
    